site_name: Exército Brasileiro - IHC 2021.2

theme:
  name: material
  language: 'pt'
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    primary: green


nav:
    - Inicio: index.md
    - Planejamento:
      - Planejamento do Projeto: planejamento.md
      - Sites Avaliados: sites_avaliados.md
      - Processo de Design: processo_design.md
      - Metodologia: metodologia.md
    - Analise de requisitos:
      - Perfil do Usuário: ./analise_requisitos/PerfilDoUsuario.md
      - Personas: ./analise_requisitos/personas.md
      - Análise de Tarefas:
        - HTA: ./analise_requisitos/AnaliseHierarquicaDeTarefas.md
        - CTT: ./analise_requisitos/ctt.md 
        - KLM: ./analise_requisitos/klm.md 
        - CMN-GOMS: ./analise_requisitos/Cmn_Goms.md 
      - Metas de Usabiliade: ./analise_requisitos/metasUsabilidade.md
      - Princípios e Diretrizes: ./analise_requisitos/PrincipiosEDiretrizes.md
      - Guia de Estilo: ./analise_requisitos/GuiaEstilo.md
    - Design, avaliação e desenvolvimento:
      - Nível 1: 
        - Storyboards: 
          - Storyboard: ./Design_avaliacao_desenv/nivel1/storyboard.md
          # - Planejamento: a.md
          - Relato dos resultados: ./Design_avaliacao_desenv/nivel1/relatoStoryboard.md
        - Análise de Tarefas:
          - Planejamento da Avaliação: ./Design_avaliacao_desenv/nivel1/PlanejamentoAnaliseTarefas.md
          - Relato dos resultados: ./Design_avaliacao_desenv/nivel1/RelatoDosResultadosAnaliseDeTarefas.md
          - Entrevistas: ./Design_avaliacao_desenv/nivel1/entrevistas.md
      - Nível 2:
        - Protótipos de papel:
          - Planejamento da Avaliação: ./Design_avaliacao_desenv/nivel2/planejamento_Avaliação.md
          - Relato dos resultados: ./Design_avaliacao_desenv/nivel2/relato_resultado_prototipo_papel.md
      - Nível 3:
        - Planejamento da Avaliação: ./Design_avaliacao_desenv/nivel3/planejamento_avaliacao_protoAltaFid.md
        - Relato dos resultados: ./Design_avaliacao_desenv/nivel3/relato_protoAltaFid.md
    - Verificação dos artefatos:
      - Introdução: ./verificação_artefatos/introducao_verificacao.md
      - Sites avaliados: ./verificação_artefatos/verificacao_Sites_Avaliados.md
      - Perfil do Usuário: ./verificação_artefatos/perfil_usuario_questionario.md
      - Personas: ./verificação_artefatos/verificacao_Personas.md
      - Analise de Tarefas: ./verificação_artefatos/verificação_Analise_Tarefas.md
      - Metas de Usabilidade: ./verificação_artefatos/verificacao_metas_de_usabilidade.md
      - Princípios e Diretrizes: ./verificação_artefatos/verificação_Princípios_diretrizes_do_projeto.md
      - Guia de Estilos: ./verificação_artefatos/GuiaDeEstilos_verificacao.md
      - Planejamento da Avaliação das Análises de Tarefas: ./verificação_artefatos/verificação_plan_avaliação_analise_tarefas.md
      - Planejamento da Avaliação dos Storyboards: ./verificação_artefatos/verificacao_plan_aval_storyboard.md
      - Storyboards: ./verificação_artefatos/verificacao_storyboard.md
      - Planejamento do Protótipo de papel: ./verificação_artefatos/verificacao_Planejamento_Prototipo_Papel.md
      - Protótipo de papel: ./verificação_artefatos/verificacao_Prototipo_Papel.md

    - Entregáveis:
      - Entrega 1: entrega1.md
      - Entrega 2: entrega2.md
      - Entrega 3: entrega3.md
      - Entrega 4: entrega4.md
      - Entrega 5: entrega5.md
      - Entrega 6: entrega6.md
      - Entrega 7: entrega7.md
      - Entrega Final: entregaFinal.md
