site_name: Exército Brasileiro - IHC 2021.2

theme:
  name: material
  language: 'pt'
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    primary: green

nav:
    - Inicio: index.md
    - Planejamento:
      - Planejamento do Projeto: planejamento.md
      - Sites Avaliados: sites_avaliados.md
      - Processo de Design: processo_design.md
      - Metodologia: metodologia.md
    - Analise de requisitos:
      - Perfil do Usuário: ./analise_requisitos/personas.md
      - Personas: ./analise_requisitos/personas.md
      - Análise de Tarefas:
        - HTA: ./analise_requisitos/personas.md
        - CTT: ./analise_requisitos/personas.md
        - KLM: ./analise_requisitos/personas.md
        - CMN-GOMS: ./analise_requisitos/personas.md
    - Entregáveis:
      - Entraga 1: entrega1.md
