site_name: Exército Brasileiro - IHC 2021.2

theme:
  name: material
  language: 'pt'
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    primary: green


nav:
    - Inicio: index.md
    - Planejamento:
      - Planejamento do Projeto: planejamento.md
      - Sites Avaliados: sites_avaliados.md
      - Processo de Design: processo_design.md
      - Metodologia: metodologia.md
    - Analise de requisitos:
      - Perfil do Usuário: ./analise_requisitos/PerfilDoUsuario.md
      - Personas: ./analise_requisitos/personas.md
      - Análise de Tarefas:
        - HTA: ./analise_requisitos/AnaliseHierarquicaDeTarefas.md
        - CTT: ./analise_requisitos/ctt.md 
        - KLM: ./analise_requisitos/klm.md 
        - CMN-GOMS: ./analise_requisitos/Cmn_Goms.md 
      - Metas de Usabiliade: ./analise_requisitos/metasUsabilidade.md
      - Princípios e Diretrizes: ./analise_requisitos/PrincipiosEDiretrizes.md
      - Guia de Estilo: ./analise_requisitos/GuiaEstilo.md
    - Entregáveis:
      - Entraga 1: entrega1.md
      - Entraga 2: entrega2.md
